-- Supabase/PostgreSQL schema for Shrishti Lending Library.
-- Run this in Supabase SQL Editor before pointing the Spring Boot app to Supabase.

create table if not exists book_status (
    status_id bigint primary key,
    description varchar(50) not null unique
);

insert into book_status (status_id, description) values
    (1, 'AVAILABLE'),
    (2, 'UNAVAILABLE'),
    (3, 'SOLD'),
    (4, 'LOST_DAMAGED'),
    (5, 'TO_BE_SOLD'),
    (6, 'OBSOLETE')
on conflict (status_id) do update
set description = excluded.description;

create table if not exists communities (
    community_id bigint primary key,
    community_name varchar(255) not null unique
);

create table if not exists offers (
    offer_id bigint generated by default as identity primary key,
    offer_name varchar(255) not null,
    community_id bigint not null references communities(community_id),
    offer_type varchar(20) not null check (offer_type in ('BUNDLE', 'PERCENT')),
    start_date date not null,
    end_date date not null,
    discount_percent numeric(5, 2),
    bundle_book_count integer,
    bundle_price numeric(10, 2),
    bundle_duration_days integer,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now()
);

alter table communities
add column if not exists active_offer_id bigint references offers(offer_id);

alter table communities
add column if not exists is_offer_active boolean not null default false;

create table if not exists login (
    username varchar(64) primary key,
    pw varchar(255) not null,
    role varchar(30) not null check (lower(role) in ('admin', 'guest'))
);

-- Add your admin user after choosing a password:
-- insert into login (username, pw, role) values ('admin', 'your-password', 'admin');

create table if not exists inventory (
    book_id bigint primary key,
    book_name varchar(255) not null,
    author varchar(255),
    genre varchar(255),
    status_id bigint references book_status(status_id),
    lending_cost numeric(10, 2) not null check (lending_cost >= 0),
    purchase_price numeric(10, 2),
    purchase_date date,
    selling_price numeric(10, 2),
    selling_date date
);

alter table inventory
add column if not exists purchase_date date;

alter table inventory
add column if not exists selling_price numeric(10, 2);

alter table inventory
add column if not exists selling_date date;

create table if not exists customers (
    customer_id varchar(64) primary key,
    customer_name varchar(255) not null,
    block_number varchar(100),
    unit_number varchar(100),
    mobile_number varchar(30),
    community_id bigint not null references communities(community_id)
);

create table if not exists transactions (
    transaction_id varchar(64) primary key,
    customer_id varchar(64) not null references customers(customer_id),
    book_id bigint not null references inventory(book_id),
    pickup_date date not null default current_date,
    return_date date,
    total_amount numeric(10, 2) not null,
    is_swap boolean default false,
    is_partially_paid boolean default false,
    amount_paid numeric(10, 2),
    offer_id bigint references offers(offer_id),
    subscription_txn_id varchar(64) references transactions(transaction_id),
    bundle_book_no integer,
    bundle_book_limit integer,
    subscription_status varchar(20),
    subscription_start_date date,
    subscription_end_date date,
    normal_amount numeric(10, 2),
    discount_amount numeric(10, 2),
    book_revenue_amount numeric(10, 2)
);

alter table transactions
add column if not exists offer_id bigint references offers(offer_id);

alter table transactions
add column if not exists subscription_txn_id varchar(64) references transactions(transaction_id);

alter table transactions
add column if not exists bundle_book_no integer;

alter table transactions
add column if not exists bundle_book_limit integer;

alter table transactions
add column if not exists subscription_status varchar(20);

alter table transactions
add column if not exists subscription_start_date date;

alter table transactions
add column if not exists subscription_end_date date;

alter table transactions
add column if not exists normal_amount numeric(10, 2);

alter table transactions
add column if not exists discount_amount numeric(10, 2);

alter table transactions
add column if not exists book_revenue_amount numeric(10, 2);

create index if not exists idx_inventory_status_id on inventory(status_id);
create index if not exists idx_inventory_book_name on inventory(lower(book_name));
create index if not exists idx_customers_community_id on customers(community_id);
create index if not exists idx_customers_customer_name on customers(lower(customer_name));
create index if not exists idx_offers_community_id on offers(community_id);
create unique index if not exists ux_offers_one_active_per_community on offers(community_id) where is_active = true;
create index if not exists idx_transactions_book_id on transactions(book_id);
create index if not exists idx_transactions_customer_id on transactions(customer_id);
create index if not exists idx_transactions_active_book on transactions(book_id) where return_date is null;
create index if not exists idx_transactions_offer_id on transactions(offer_id);
create index if not exists idx_transactions_subscription_txn_id on transactions(subscription_txn_id);
create index if not exists idx_transactions_active_subscription on transactions(customer_id, subscription_txn_id) where subscription_status = 'ACTIVE';
